name: Create and Merge PR

on:
  workflow_dispatch:

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    env:
      ACTIONS_BOT_TOKEN: ${{ github.token }}
      USER_TOKEN: ${{ secrets.TOKEN }}
      TIMESTAMP: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
        
      - name: Set Timestamp
        run: |
          echo "TIMESTAMP=$(date '+%Y-%m-%d_%H%M_UTC')" >> $GITHUB_ENV
          
      - name: Create New Branch
        run: |
          git config --global user.email "github_action@example.com"
          git config --global user.name "cvelistV5 Github Action"
          git switch --create bot_pr_branch
          echo "github actions bot was here ${TIMESTAMP}" >> bot_file.txt
          git add -f bot_file.txt
          git commit -m "bot commit ${TIMESTAMP}"
          git push -u origin bot_pr_branch
      
      - name: Create Pull Request
        run: |
          echo "${{ steps.app-token.outputs.token }}" > apptoken.txt
          gh auth login --with-token < apptoken.txt
          # echo "${ACTIONS_BOT_TOKEN}" > bottoken.txt
          # gh auth login --with-token < bottoken.txt
          gh pr create --title "bot pr ${TIMESTAMP}" --body "a bot made this pr" --base main --head bot_pr_branch

      - name: Approve Pull Request
        run: |
          echo "${USER_TOKEN}" > mytoken.txt
          gh auth login --with-token < mytoken.txt
          # echo "${{ steps.app-token.outputs.token }}" > apptoken.txt
          # gh auth login --with-token < apptoken.txt
          gh pr review bot_pr_branch --approve

      - name: Merge Pull Request
        run: |
          # echo "${{ steps.app-token.outputs.token }}" > apptoken.txt
          # gh auth login --with-token < apptoken.txt
          echo "${ACTIONS_BOT_TOKEN}" > bottoken.txt
          gh auth login --with-token < bottoken.txt
          gh pr merge bot_pr_branch --merge --admin --delete-branch
