name: Create and Merge PR

on:
  workflow_dispatch: # can only be run via GH website

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    env:
      ACTIONS_BOT_TOKEN: ${{ github.token }}
      USER_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create New Branch
        run: |
          echo "${ACTIONS_BOT_TOKEN}" > bottoken.txt
          gh auth login --with-token < bottoken.txt
          git switch --create pr_branch
          echo "github actions bot was here" > bot_file.txt
          git add -f bot_file.txt
          git commit -m "bot commit"
          git push -u origin pr_branch
      
      - name: Create Pull Request
        run: |
          gh pr create --title "test pr" --body "a bot made this pr" --base main --head pr_branch

      - name: Approve Pull Request
        run: |
          echo "${USER_TOKEN}" > mytoken.txt
          gh auth login --with-token < mytoken.txt
          gh pr review pr_branch --approve

      - name: Merge Pull Request
        run: |
          gh auth login --with-token < bottoken.txt
          gh pr merge pr_branch --merge --admin --delete-branch
