name: Create and Merge PR

on:
  workflow_dispatch: # can only be run via GH website

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Switch to branch
      #   run: |
      #     gh checkout pr_branch
      
      - name: Create Pull Request
        run: |
          gh pr create --title "test pr" --body "a bot made this pr" --base main --head pr_branch

      - name: Approve Pull Request
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr review pr_branch --approve

      - name: Merge Pull Request
        run: |
          gh pr merge pr_branch --merge --admin --delete-branch
