name: Create and Merge PR

on:
  workflow_dispatch: # can only be run via GH website

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    env:
      ACTIONS_BOT_TOKEN: ${{ github.token }}
      USER_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Switch to branch
      #   run: |
      #     gh checkout pr_branch
      - name: Create New Branch
        run: |
          echo "${ACTIONS_BOT_TOKEN}" > bottoken.txt
          gh auth login --with-token < bottoken.txt
          gh codespace create --branch pr_branch
          echo "jack was here" > new_file.txt
          git checkout pr_branch
          git add new_file.txt
          git commit -m "commit to be merged"
          git push
      
      - name: Create Pull Request
        run: |
          gh pr create --title "test pr" --body "a bot made this pr" --base main --head pr_branch

      - name: Approve Pull Request
        run: |
          echo "${USER_TOKEN}" > mytoken.txt
          gh auth login --with-token < mytoken.txt
          gh pr review pr_branch --approve

      - name: Merge Pull Request
        run: |
          gh pr merge pr_branch --merge --admin --delete-branch
