name: Create and Merge PR

on:
  workflow_dispatch: # can only be run via GH website

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Switch to branch
        run: |
          gh checkout pr_branch
      
      - name: Create Pull Request
        run: |
          gh pr create --title "test pr" --body "a bot made this pr" --base main

      - name: Merge Pull Request
        run: |
          gh pr merge --merge --delete-branch
