# GitHub Action to remove a CVE last updated 5+ hours ago from main.


name: Remove CVE

on:
  workflow_dispatch: # can only be run via GH website

jobs:
  remove_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove CVE-2024-5379 =
        run: |
          git config --global user.email "jackflores.swe@gmail.com"
          git config --global user.name "jackflores-swe"
          git rm cves/2024/5xxx/CVE-2024-5379.json # hardcoded for simplicity
          git commit -m "remove CVE"
          git push origin main
